# Generated by Django 4.2.11 on 2026-03-16 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='prescribed_drugs',
            field=models.TextField(blank=True, help_text='List of prescribed drugs with dosages', null=True),
        ),
    ]
