# Generated by Django 6.0.3 on 2026-03-16 10:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_labtest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Medicine',
            new_name='PharmacyItem',
        ),
        migrations.CreateModel(
            name='PharmacyIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued', models.PositiveIntegerField()),
                ('issued_date', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.patient')),
                ('pharmacy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.pharmacyitem')),
            ],
            options={
                'ordering': ['-issued_date'],
            },
        ),
        migrations.DeleteModel(
            name='MedicineIssue',
        ),
    ]
