# Generated by Django 6.0.3 on 2026-03-21 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_mpesa_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='mpesatransaction',
            name='confirmation_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Sent', 'Sent'), ('Confirmed', 'Confirmed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bill',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Card', 'Card'), ('Insurance', 'Insurance'), ('Bank Transfer', 'Bank Transfer'), ('M-Pesa', 'M-Pesa'), ('Other', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Success', 'Success'), ('Failed', 'Failed'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
