# Generated by Django 6.0.3 on 2026-03-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_mpesatransaction_confirmation_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mpesatransaction',
            name='confirmation_status',
        ),
        migrations.AlterField(
            model_name='mpesatransaction',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20),
        ),
    ]
