# Generated by Django 6.0.3 on 2026-03-23 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_remove_mpesatransaction_confirmation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mpesa_payment',
            field=models.CharField(blank=True, help_text='M-Pesa phone number for payment (format: 254XXXXXXXXX)', max_length=15, null=True),
        ),
    ]
