# Generated by Django 6.0.3 on 2026-03-23 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_bill_mpesa_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, help_text='M-Pesa receipt number', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='mpesa_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Success', 'Success'), ('Failed', 'Failed')], help_text='M-Pesa payment status', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='mpesa_timestamp',
            field=models.DateTimeField(blank=True, help_text='M-Pesa payment completion time', null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='mpesa_transaction_id',
            field=models.CharField(blank=True, help_text='M-Pesa transaction ID', max_length=100, null=True),
        ),
    ]
